//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right_up {
            get {
                object obj = ResourceManager.GetObject("arrow_right-up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 resTurrets.stuff
        ///resPlaceableAmarr.stuff
        ///resPlaceableCaldari.stuff
        ///resPlaceableGallente.stuff
        ///resPlaceableGeneric.stuff
        ///resPlaceableMinmatar.stuff 的本地化字符串。
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 resDX9PlanetsCloudDense.stuff
        ///resDX9PlanetsCloudSparse.stuff
        ///resDX9PlanetsGas.stuff
        ///resDX9PlanetsIce.stuff
        ///resDX9PlanetsLava.stuff
        ///resDX9PlanetsOther.stuff
        ///resDX9PlanetsSandstorm.stuff
        ///resDX9PlanetsTerrestrialC.stuff
        ///resDX9PlanetsTerrestrialT.stuff
        ///resDX9PlanetsThunderstorm.stuff 的本地化字符串。
        /// </summary>
        internal static string Plantes {
            get {
                return ResourceManager.GetString("Plantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap save_diskette_floppy_disk {
            get {
                object obj = ResourceManager.GetObject("save_diskette_floppy_disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 resDX9AmarrShips00.stuff
        ///resDX9AmarrShips01.stuff
        ///resDX9AmarrShips02.stuff
        ///resDX9CaldariShips00.stuff
        ///resDX9CaldariShips01.stuff
        ///resDX9CaldariShips02.stuff
        ///resDX9CONCORDShips.stuff
        ///resDX9GallenteShips00.stuff
        ///resDX9GallenteShips01.stuff
        ///resDX9JoveShips.stuff
        ///resDX9MinmatarShips00.stuff
        ///resDX9MinmatarShips01.stuff
        ///resDX9OREShips.stuff
        ///resDX9PiratesShips.stuff
        ///resDX9Shipwrecks.stuff
        ///resDX9SOCTShips.stuff
        ///resDX9SpecialShips.stuff
        ///resDX9Drones.stuff 的本地化字符串。
        /// </summary>
        internal static string ShipsAndDrones {
            get {
                return ResourceManager.GetString("ShipsAndDrones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 resDX9AsteroidStations.stuff
        ///resDX9BattleStations.stuff
        ///resDX9SanshaStations.stuff
        ///resInteriorAmarr.stuff
        ///resInteriorCaldari.stuff
        ///resInteriorEffect.stuff
        ///resInteriorGallente.stuff
        ///resInteriorMinmatar.stuff
        ///resInteriorRadiosityCache.stuff
        ///resInteriorShared.stuff 的本地化字符串。
        /// </summary>
        internal static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap time_clock1 {
            get {
                object obj = ResourceManager.GetObject("time_clock1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string TitleInfo {
            get {
                return ResourceManager.GetString("TitleInfo", resourceCulture);
            }
        }
    }
}
